update documentation
bluepy/calc pull request #1
Opened 2020-03-29 23:54 UTC by rchamarthy

Signed-off-by: Ravi Chamarthy <ravchama@cisco.com>

2020-03-29 23:58 UTC, Ace369 commented on README.md
> +    * add
Describe what add does.

2020-03-29 23:59 UTC, IJ0717 commented on README.md
> +    * subtract
describe subtract

2020-03-30 00:01 UTC, Ace369 commented on README.md
> -calculator implementation in python
Capitalize the titles.

2020-03-30 00:02 UTC, suhanimv requested changes

2020-03-30 00:02 UTC, suhanimv commented on README.md
> +    * multiply
obtain a number from multiplying two different numbers. ex. 6*8=48

2020-03-30 00:06 UTC, suhanimv approved these changes

2020-03-30 00:07 UTC, IJ0717 approved these changes

2020-03-30 00:07 UTC, Ace369 approved these changes

2020-03-30 00:08 UTC, merged